name: Update league table status
on:
  schedule:
    - cron: "0 */8 * * *"
  workflow_dispatch:

jobs:
  upload-league-table-status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
          architecture: x64
      - name: Install dependencies
        run: pip install -e .
      - name: Fetch Football league table and update MaccabiPedia
        env:
          PYWIKIBOT_DIR: src/maccabipediabot/pywikibot_configs/
          MACCABIPEDIA_BOT_USERNAME: ${{ secrets.MACCABIPEDIA_BOT_USERNAME }}
          MACCABIPEDIA_BOT_PASSWORD: ${{ secrets.MACCABIPEDIA_BOT_PASSWORD }}
        run: python -m maccabipediabot.football.update_league_table
      - name: Fetch Volleyball league table and update MaccabiPedia
        env:
          PYWIKIBOT_DIR: src/maccabipediabot/pywikibot_configs/
          MACCABIPEDIA_BOT_USERNAME: ${{ secrets.MACCABIPEDIA_BOT_USERNAME }}
          MACCABIPEDIA_BOT_PASSWORD: ${{ secrets.MACCABIPEDIA_BOT_PASSWORD }}
        run: python -m maccabipediabot.volleyball.update_league_table_volleyball
      - name: Fetch Basketball league table and update MaccabiPedia
        env:
          PYWIKIBOT_DIR: src/maccabipediabot/pywikibot_configs/
          MACCABIPEDIA_BOT_USERNAME: ${{ secrets.MACCABIPEDIA_BOT_USERNAME }}
          MACCABIPEDIA_BOT_PASSWORD: ${{ secrets.MACCABIPEDIA_BOT_PASSWORD }}
        run: python -m maccabipediabot.basketball.update_league_table_basketball
      - name: Fetch Basketball euroleague table and update MaccabiPedia
        env:
          PYWIKIBOT_DIR: src/maccabipediabot/pywikibot_configs/
          MACCABIPEDIA_BOT_USERNAME: ${{ secrets.MACCABIPEDIA_BOT_USERNAME }}
          MACCABIPEDIA_BOT_PASSWORD: ${{ secrets.MACCABIPEDIA_BOT_PASSWORD }}
        run: python -m maccabipediabot.basketball.update_euroleague_table_basketball
  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
