name: Upload MaccabiPedia Games FTP
on:
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch:

jobs:
  maccabipedia-games-to-maccabipedia-host:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
          architecture: x64
      - uses: astral-sh/setup-uv@v6
      - name: Install dependencies
        run: uv sync
      - name: Fetch MaccabiPedia Data
        run: uv run python -m maccabistats.github_actions_scripts.fetch_games_from_maccabipedia
      - name: Upload Games File To MaccabiPedia FTP
        env:
          MACCABIPEDIA_FTP: ${{ secrets.MACCABIPEDIA_FTP }}
          MACCABIPEDIA_FTP_USERNAME: ${{ secrets.MACCABIPEDIA_FTP_USERNAME }}
          MACCABIPEDIA_FTP_PASSWORD: ${{ secrets.MACCABIPEDIA_FTP_PASSWORD }}
        run: uv run python -m maccabistats.github_actions_scripts.upload_maccabipedia_games_to_ftp
      - name: Notify Telegram Latest Games Uploaded
        uses: appleboy/telegram-action@v2.25.0
        with:
          to: ${{ secrets.MACCABIPEDIA_ERRORS_TELEGRAM_TO }}
          token: ${{ secrets.MACCABIPEDIA_ERRORS_TELEGRAM_TOKEN }}
          message: Latest MaccabiPedia games uploaded to our FTP
  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
