name: Upload Last Game To MaccabiPedia
on:
  workflow_dispatch:
  repository_dispatch:
    types: [ zapier_trigger ]

jobs:
  upload-last-game-to-maccabipedia:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
          architecture: x64
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Fetch Games From MaccabiTLVSite
        run: python fetch_games_from_maccabi_tlv_site.py
      - name: Upload Last Game To MaccabiPedia
        env:
          PYWIKIBOT_DIR: pywikibot_configs/
          MACCABIPEDIA_BOT_USERNAME: ${{ secrets.MACCABIPEDIA_BOT_USERNAME }}
          MACCABIPEDIA_BOT_PASSWORD: ${{ secrets.MACCABIPEDIA_BOT_PASSWORD }}
        run: python upload_last_game_to_maccabipedia.py