name: Upload Last Game To MaccabiPedia
on:
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch:

jobs:
  upload-last-game-to-maccabipedia:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
          architecture: x64
      - name: Install dependencies
        run: python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Fetch Last Game And Upload To MaccabiPedia
        run: python fetch_and_upload_last_game_to_maccabipedia.py.py